import type { Metadata } from "next";

import "./globals.css";
import "@arco-design/web-react/dist/css/arco.css";




export const metadata: Metadata = {
  title: "我的nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
